version: '3.8'

services:
  easycopy-server:
    image: vikingkom/easycopy-server:latest
    ports:
      - "${EASYCOPY_PORT:-8000}:8000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=${TZ:-UTC}
      - VITE_API_URL=${EASYCOPY_DOMAIN:-http://localhost:8000}
    container_name: easycopy-server
